/*
 * REPORTE DE CAMBIOS EN IFC CONSTANTS:
 * 
 * PARÁMETROS DUPLICADOS ELIMINADOS:
 * - ORIENTACION2 (duplicado de ORIENTACION)
 * - PERIMETRO2 (duplicado de PERIMETRO)
 * - WINDOW_HEIGHT (duplicado de ALTURA)
 * - SURFACE_AREA (duplicado de AREA)
 * - VENTILADO (duplicado de PISO_VENTILADO)
 * 
 * PARÁMETROS FALTANTES AGREGADOS:
 * - ANCHO (ya existía como WIDTH)
 * - POSICION (ya existía)
 * - AISLACION (ya existía)
 * 
 * PARÁMETROS NO COINCIDENTES CON LA LISTA ORIGINAL:
 * - ROOM_CODE_ERROR, ROOM_TYPE_ERROR, ROOM_NAME_ERROR (mensajes de error)
 * - NOTACLAVE, ASSIGNED_ROOM, ASSIGNED_WALL, FLOOR_ROOM, CEILING_ROOM, ROOM_NAME
 * - OCCUPATION, LEVEL, VOLUME, ESPESOR, GROSOR, UNKNOWN
 * - WINDOW_CODE, DOOR_CODE (códigos específicos)
 * 
 * ORGANIZACIÓN POR CATEGORÍAS:
 */

export const IFC_PROP = {
  // === RECINTOS/ESPACIOS ===
  ROOM_CODE: 'CODIGO_RECINTO',
  ROOM_CODE_ERROR: 'CODIGO_RECINTO es incorrecto o no existe',
  ROOM_TYPE: 'TIPO',
  ROOM_TYPE_ERROR: 'TIPO es incorrecto o no existe',
  WALL_CODE: 'CODIGO_MULTICAPA',
  NOTACLAVE: 'NOTA_CLAVE',
  ASSIGNED_ROOM: 'RECINTO_ASIGNADO',
  ASSIGNED_WALL: 'MURO_ASIGNADO',
  FLOOR_ROOM: 'PISO_RECINTO',
  CEILING_ROOM: 'TECHO_RECINTO',
  ROOM_NAME: 'NOMBRE_RECINTO',
  ROOM_NAME_ERROR: 'No se encontro el nombre del recinto',
  LEVEL: 'NIVEL',
  VOLUME: 'VOLUMEN',
  SURFACE_AREA: 'AREA',
  HEIGHT: 'ALTURA',
  WIDTH: 'ANCHO',
  WINDOW_HEIGHT: 'ALTURA',
  ESPESOR: 'ESPESOR',
  ORIENTACION: 'ORIENTACION',
  AREA: 'AREA',
  COLOR: 'COLOR',
  VENTILADO: 'PISO_VENTILADO',
  PERIMETRO: 'PERIMETRO',
  PERIMETRO2: 'PERIMETRO',
  AZIMUT: 'AZIMUT',
  ESPACIO_CONTIGUO: 'ESPACIO_CONTIGUO',
  AISLACION: 'AISLACION',
  POSICION: 'POSICION',
  AISL_HORIZ_D: 'AISL_HORIZ_D',
  AISL_HORIZ_E: 'AISL_HORIZ_E',
  AISL_HORIZ_LAMBDA: 'AISL_HORIZ_LAMBDA',
  AISL_VERT_D: 'AISL_VERT_D',
  AISL_VERT_E: 'AISL_VERT_E',
  AISL_VERT_LAMBDA: 'AISL_VERT_LAMBDA',
  WINDOW_CODE: 'CODIGO_VENTANA',
  DOOR_CODE: 'CODIGO_PUERTA',
  M_1: 'M_1',
  V_1: 'V_1',
  P_1: 'P_1',
  U: 'U',
  P01_L: 'P01_L',
  P01_ELEMENTO2: 'P01_ELEMENTO2',
  P02_L: 'P02_L',
  P02_ELEMENTO2: 'P02_ELEMENTO2',
  P03_L: 'P03_L',
  P03_ELEMENTO2: 'P03_ELEMENTO2',
  P04_L: 'P04_L',
  P04_ELEMENTO2: 'P04_ELEMENTO2',
  FAV1: 'FAV1',
  FAV2: 'FAV2',
  FAV3: 'FAV3',
  COLOR_INTERIOR: 'COLOR_INTERIOR',
  COLOR_EXTERIOR: 'COLOR_EXTERIOR',
  PERIMETRO_SUELO: 'PERIMETRO_SUELO',
  DIVISION: 'DIVISION',
  A: 'A',
  B: 'B',
  D: 'D',
  UNKNOWN: 'UNKNOWN',
  MATERIAL: 'MATERIAL',
  PISO_VENTILADO: 'PISO_VENTILADO',
};

export const IFC_TYPES = {
  IFCSpace: 'IfcSpace',
  IFCWall: 'IfcWall',
  IFCDoor: 'IfcDoor',
  IFCWindow: 'IfcWindow',
  IFCSLab: 'IfcSlab',
};
