/*
 * REPORTE DE CAMBIOS EN IFC CONSTANTS:
 * 
 * PARÁMETROS DUPLICADOS ELIMINADOS:
 * - ORIENTACION2 (duplicado de ORIENTACION)
 * - PERIMETRO2 (duplicado de PERIMETRO)
 * - WINDOW_HEIGHT (duplicado de ALTURA)
 * - SURFACE_AREA (duplicado de AREA)
 * - VENTILADO (duplicado de PISO_VENTILADO)
 * 
 * PARÁMETROS FALTANTES AGREGADOS:
 * - ANCHO (ya existía como WIDTH)
 * - POSICION (ya existía)
 * - AISLACION (ya existía)
 * 
 * PARÁMETROS NO COINCIDENTES CON LA LISTA ORIGINAL:
 * - ROOM_CODE_ERROR, ROOM_TYPE_ERROR, ROOM_NAME_ERROR (mensajes de error)
 * - NOTACLAVE, ASSIGNED_ROOM, ASSIGNED_WALL, FLOOR_ROOM, CEILING_ROOM, ROOM_NAME
 * - OCCUPATION, LEVEL, VOLUME, ESPESOR, GROSOR, UNKNOWN
 * - WINDOW_CODE, DOOR_CODE (códigos específicos)
 * 
 * ORGANIZACIÓN POR CATEGORÍAS:
 */

export const IFC_PROP = {
  // === RECINTOS/ESPACIOS ===
  ROOM_CODE: 'CODIGO_RECINTO',
  ROOM_CODE_ERROR: 'CODIGO_RECINTO es incorrecto o no existe',
  ROOM_TYPE: 'OCUPACION',
  ROOM_TYPE_ERROR: 'OCUPACION es incorrecto o no existe',
  ROOM_NAME: 'NOMBRE_RECINTO',
  ROOM_NAME_ERROR: 'No se encontro el nombre del recinto',
  ASSIGNED_ROOM: 'RECINTO_ASIGNADO',
  OCCUPATION: 'OCUPACION',
  TIPO: 'TIPO',
  NIVEL: 'NIVEL',
  LEVEL: 'NIVEL',
  AREA: 'AREA',
  VOLUME: 'VOLUMEN',
  ALTURA: 'ALTURA',
  HEIGHT: 'ALTURA',
  PERIMETRO: 'PERIMETRO',
  PERIMETRO_SUELO: 'PERIMETRO_SUELO',
  
  // === PISOS Y TECHOS ===
  FLOOR_ROOM: 'PISO_RECINTO',
  CEILING_ROOM: 'TECHO_RECINTO',
  PISO_VENTILADO: 'PISO_VENTILADO',
  
  // === MUROS ===
  WALL_CODE: 'CODIGO_MULTICAPA',
  CODIGO_MULTICAPA: 'CODIGO_MULTICAPA',
  ASSIGNED_WALL: 'MURO_ASIGNADO',
  M_1: 'M_1',
  MATERIAL: 'MATERIAL',
  COLOR: 'COLOR',
  ESPESOR: 'ESPESOR',
  GROSOR: 'GROSOR',
  ORIENTACION: 'ORIENTACION',
  ESPACIO_CONTIGUO: 'ESPACIO_CONTIGUO',
  AZIMUT: 'AZIMUT',
  
  // === PUERTAS ===
  DOOR_CODE: 'CÓDIGO DE PUERTA',
  CODIGO_PUERTA: 'CODIGO_PUERTA',
  
  // === VENTANAS ===
  WINDOW_CODE: 'CÓDIGO DE VENTANA',
  CODIGO_VENTANA: 'CODIGO_VENTANA',
  ANCHO: 'ANCHO',
  WIDTH: 'ANCHO',
  ALTO: 'ALTO',
  POSICION: 'POSICIÓN',
  AISLACION: 'AISLACIÓN',
  
  // === AISLACIÓN TÉRMICA ===
  AISL_VERT_LAMBDA: 'AISL_VERT_LAMBDA',
  AISL_VERT_E: 'AISL_VERT_E',
  AISL_VERT_D: 'AISL_VERT_D',
  AISL_HORIZ_LAMBDA: 'AISL_HORIZ_LAMBDA',
  AISL_HORIZ_E: 'AISL_HORIZ_E',
  AISL_HORIZ_D: 'AISL_HORIZ_D',
  
  // === OTROS PARÁMETROS ===
  DIVISION: 'DIVISION',
  A: 'A',
  B: 'B',
  D: 'D',
  
  // === CONSTANTES TÉCNICAS ===
  NOTACLAVE: 'NOTA CLAVE',
  UNKNOWN: 'UNKNOWN',
};

export const IFC_TYPES = {
  IFCSpace: 'IfcSpace',
  IFCWall: 'IfcWall',
  IFCDoor: 'IfcDoor',
  IFCWindow: 'IfcWindow',
  IFCSLab: 'IfcSlab',
};
