// src/data/locationData.ts

export interface LocationData {
    [country: string]: {
      departments: {
        [department: string]: string[];
      };
    };
  }
  
  const locationData: LocationData = {
    Perú: {
      departments: {
        Amazonas: [
          "Chachapoyas",
          "Bagua",
          "Bongará",
          "Condorcanqui",
          "Luya",
          "Rodríguez de Mendoza",
          "Utcubamba",
        ],
        Ancash: [
          "Huaraz",
          "Aija",
          "Antonio Raymondi",
          "Asunción",
          "Bolognesi",
          "Carhuaz",
          "Carlos Fermín Fitzcarrald",
          "Casma",
          "Corongo",
          "Huari",
          "Huarmey",
          "Huaylas",
          "Mariscal Luzuriaga",
          "Ocros",
          "Pallasca",
          "Pomabamba",
          "Recuay",
          "Santa",
          "Sihuas",
          "Yungay",
        ],
        Apurímac: [
          "Abancay",
          "Andahuaylas",
          "Antabamba",
          "Aymaraes",
          "Cotabambas",
          "Chincheros",
          "Grau",
        ],
        Arequipa: [
          "Arequipa",
          "Camaná",
          "Caravelí",
          "Castilla",
          "Caylloma",
          "Condesuyos",
          "Islay",
          "La Unión",
        ],
        Ayacucho: [
          "Huamanga",
          "Cangallo",
          "Huanca Sancos",
          "Huanta",
          "La Mar",
          "Lucanas",
          "Parinacochas",
          "Páucar del Sara Sara",
          "Sucre",
          "Vilcas Huamán",
          "Víctor Fajardo",
        ],
        Cajamarca: [
          "Cajamarca",
          "Cajabamba",
          "Celendín",
          "Chota",
          "Contumazá",
          "Cutervo",
          "Hualgayoc",
          "Jaén",
          "San Ignacio",
          "San Marcos",
          "San Miguel",
          "San Pablo",
          "Santa Cruz",
        ],
        Callao: ["Callao"],
        Cusco: [
          "Cusco",
          "Acomayo",
          "Anta",
          "Calca",
          "Canas",
          "Canchis",
          "Chumbivilcas",
          "Espinar",
          "La Convención",
          "Paruro",
          "Paucartambo",
          "Quispicanchi",
          "Urubamba",
        ],
        Huancavelica: [
          "Huancavelica",
          "Acobambilla",
          "Acoria",
          "Churcampa",
          "Huaytará",
          "Tayacaja",
        ],
        Huánuco: [
          "Huánuco",
          "Ambo",
          "Dos de Mayo",
          "Huacaybamba",
          "Huamalíes",
          "Leoncio Prado",
          "Marías",
          "Pachitea",
          "Puerto Inca",
          "Lauricocha",
          "Yarowilca",
        ],
        Ica: ["Ica", "Chincha", "Nazca", "Palpa", "Pisco"],
        Junín: [
          "Huancayo",
          "Concepción",
          "Chanchamayo",
          "Chupaca",
          "Cochas",
          "Huancayo",
          "Huasahuasi",
          "Jauja",
          "Junín",
          "Satipo",
          "Tarma",
          "Yauli",
        ],
        "La Libertad": [
          "Trujillo",
          "Ascope",
          "Bolívar",
          "Chepén",
          "Julcán",
          "Otuzco",
          "Pacasmayo",
          "Pataz",
          "Sánchez Carrión",
          "Santiago de Chuco",
          "Gran Chimú",
          "Virú",
        ],
        Lambayeque: ["Chiclayo", "Ferreñafe", "Lambayeque"],
        Lima: [
          "Lima",
          "Barranca",
          "Cajatambo",
          "Canta",
          "Cañete",
          "Huaral",
          "Huarochirí",
          "Huaura",
          "Oyón",
          "Yauyos",
        ],
        Loreto: [
          "Maynas",
          "Alto Amazonas",
          "Loreto",
          "Mariscal Ramón Castilla",
          "Requena",
          "Ucayali",
        ],
        "Madre de Dios": ["Tambopata", "Manu", "Tahuamanu"],
        Moquegua: ["Mariscal Nieto", "General Sánchez Cerro", "Ilo"],
        Pasco: ["Pasco", "Daniel Alcides Carrión", "Oxapampa"],
        Piura: [
          "Piura",
          "Ayabaca",
          "Huancabamba",
          "Morropon",
          "Paita",
          "Sullana",
          "Talara",
          "Sechura",
        ],
        Puno: [
          "Puno",
          "Azángaro",
          "Carabaya",
          "Chucuito",
          "El Collao",
          "Melgar",
          "Moho",
          "San Antonio de Putina",
          "San Román",
          "Sandia",
          "Yunguyo",
        ],
        "San Martín": [
          "Moyobamba",
          "Bellavista",
          "El Dorado",
          "Huallaga",
          "Lamas",
          "Mariscal Cáceres",
          "Picota",
          "Rioja",
          "San Martín",
          "Tocache",
        ],
        Tacna: ["Tacna", "Candarave", "Jorge Basadre", "Tarata"],
        Tumbes: ["Tumbes", "Contralmirante Villar", "Zarumilla"],
        Ucayali: ["Coronel Portillo", "Atalaya", "Padre Abad", "Purús"],
      },
    },
    Chile: {
      departments: {
        "Región de Arica y Parinacota": ["Arica", "Parinacota"],
        "Región de Tarapacá": ["Iquique", "El Tamarugal"],
        "Región de Antofagasta": ["Antofagasta", "El Loa", "Tocopilla"],
        "Región de Atacama": ["Copiapó", "Chañaral", "Huasco"],
        "Región de Coquimbo": ["Elqui", "Choapa", "Limarí"],
        "Región de Valparaíso": [
          "Valparaíso",
          "Isla de Pascua",
          "Los Andes",
          "Petorca",
          "Quillota",
          "San Antonio",
          "San Felipe de Aconcagua",
          "Marga Marga",
        ],
        "Región del Libertador General Bernardo O'Higgins": [
          "Rancagua",
          "Cachapoal",
          "Cardenal Caro",
          "Colchagua",
        ],
        "Región del Maule": [
          "Talca",
          "Cauquenes",
          "Curicó",
          "Linares",
          "Talca",
        ],
        "Región de Ñuble": ["Diguillín", "Itata", "Punilla"],
        "Región del Biobío": ["Concepción", "Arauco", "Bío Bío"],
        "Región de La Araucanía": ["Cautín", "Malleco"],
        "Región de Los Ríos": ["Valdivia", "Ranco"],
        "Región de Los Lagos": ["Lagos", "Osorno", "Chiloé"],
        "Región de Aysén del General Carlos Ibáñez del Campo": [
          "Aysén",
          "Capitán Prat",
          "Coihaique",
          "General Carrera",
        ],
        "Región de Magallanes y de la Antártica Chilena": [
          "Magallanes",
          "Antártica",
          "Tierra del Fuego",
          "Última Esperanza",
        ],
      },
    },
  };
  
  export default locationData;
  