// src/data/locationData.ts

export interface LocationData {
    [country: string]: {
      departments: {
        [department: string]: string[];
      };
    };
  }
  
  const locationData: LocationData = {
    Perú: {
      departments: {
        Amazonas: [
          "Chachapoyas",
          "Bagua",
          "Bongará",
          "Condorcanqui",
          "Luya",
          "Rodríguez de Mendoza",
          "Utcubamba",
        ],
        Ancash: [
          "Huaraz",
          "Aija",
          "Antonio Raymondi",
          "Asunción",
          "Bolognesi",
          "Carhuaz",
          "Carlos Fermín Fitzcarrald",
          "Casma",
          "Corongo",
          "Huari",
          "Huarmey",
          "Huaylas",
          "Mariscal Luzuriaga",
          "Ocros",
          "Pallasca",
          "Pomabamba",
          "Recuay",
          "Santa",
          "Sihuas",
          "Yungay",
        ],
        Apurímac: [
          "Abancay",
          "Andahuaylas",
          "Antabamba",
          "Aymaraes",
          "Cotabambas",
          "Chincheros",
          "Grau",
        ],
        Arequipa: [
          "Arequipa",
          "Camaná",
          "Caravelí",
          "Castilla",
          "Caylloma",
          "Condesuyos",
          "Islay",
          "La Unión",
        ],
        Ayacucho: [
          "Huamanga",
          "Cangallo",
          "Huanca Sancos",
          "Huanta",
          "La Mar",
          "Lucanas",
          "Parinacochas",
          "Páucar del Sara Sara",
          "Sucre",
          "Vilcas Huamán",
          "Víctor Fajardo",
        ],
        Cajamarca: [
          "Cajamarca",
          "Cajabamba",
          "Celendín",
          "Chota",
          "Contumazá",
          "Cutervo",
          "Hualgayoc",
          "Jaén",
          "San Ignacio",
          "San Marcos",
          "San Miguel",
          "San Pablo",
          "Santa Cruz",
        ],
        Callao: ["Callao"],
        Cusco: [
          "Cusco",
          "Acomayo",
          "Anta",
          "Calca",
          "Canas",
          "Canchis",
          "Chumbivilcas",
          "Espinar",
          "La Convención",
          "Paruro",
          "Paucartambo",
          "Quispicanchi",
          "Urubamba",
        ],
        Huancavelica: [
          "Huancavelica",
          "Acobambilla",
          "Acoria",
          "Churcampa",
          "Huaytará",
          "Tayacaja",
        ],
        Huánuco: [
          "Huánuco",
          "Ambo",
          "Dos de Mayo",
          "Huacaybamba",
          "Huamalíes",
          "Leoncio Prado",
          "Marías",
          "Pachitea",
          "Puerto Inca",
          "Lauricocha",
          "Yarowilca",
        ],
        Ica: ["Ica", "Chincha", "Nazca", "Palpa", "Pisco"],
        Junín: [
          "Huancayo",
          "Concepción",
          "Chanchamayo",
          "Chupaca",
          "Cochas",
          "Huancayo",
          "Huasahuasi",
          "Jauja",
          "Junín",
          "Satipo",
          "Tarma",
          "Yauli",
        ],
        "La Libertad": [
          "Trujillo",
          "Ascope",
          "Bolívar",
          "Chepén",
          "Julcán",
          "Otuzco",
          "Pacasmayo",
          "Pataz",
          "Sánchez Carrión",
          "Santiago de Chuco",
          "Gran Chimú",
          "Virú",
        ],
        Lambayeque: ["Chiclayo", "Ferreñafe", "Lambayeque"],
        Lima: [
          "Lima",
          "Barranca",
          "Cajatambo",
          "Canta",
          "Cañete",
          "Huaral",
          "Huarochirí",
          "Huaura",
          "Oyón",
          "Yauyos",
        ],
        Loreto: [
          "Maynas",
          "Alto Amazonas",
          "Loreto",
          "Mariscal Ramón Castilla",
          "Requena",
          "Ucayali",
        ],
        "Madre de Dios": ["Tambopata", "Manu", "Tahuamanu"],
        Moquegua: ["Mariscal Nieto", "General Sánchez Cerro", "Ilo"],
        Pasco: ["Pasco", "Daniel Alcides Carrión", "Oxapampa"],
        Piura: [
          "Piura",
          "Ayabaca",
          "Huancabamba",
          "Morropon",
          "Paita",
          "Sullana",
          "Talara",
          "Sechura",
        ],
        Puno: [
          "Puno",
          "Azángaro",
          "Carabaya",
          "Chucuito",
          "El Collao",
          "Melgar",
          "Moho",
          "San Antonio de Putina",
          "San Román",
          "Sandia",
          "Yunguyo",
        ],
        "San Martín": [
          "Moyobamba",
          "Bellavista",
          "El Dorado",
          "Huallaga",
          "Lamas",
          "Mariscal Cáceres",
          "Picota",
          "Rioja",
          "San Martín",
          "Tocache",
        ],
        Tacna: ["Tacna", "Candarave", "Jorge Basadre", "Tarata"],
        Tumbes: ["Tumbes", "Contralmirante Villar", "Zarumilla"],
        Ucayali: ["Coronel Portillo", "Atalaya", "Padre Abad", "Purús"],
    },
  },
  Chile: {
    departments: {
      "Región de Arica y Parinacota": ["Arica", "Parinacota"],
      "Región de Tarapacá": ["Iquique", "El Tamarugal"],
      "Región de Antofagasta": ["Antofagasta", "El Loa", "Tocopilla"],
      "Región de Atacama": ["Copiapó", "Chañaral", "Huasco"],
      "Región de Coquimbo": ["Elqui", "Choapa", "Limarí"],
      "Región de Valparaíso": [
        "Valparaíso",
        "Isla de Pascua",
        "Los Andes",
        "Petorca",
        "Quillota",
        "San Antonio",
        "San Felipe de Aconcagua",
        "Marga Marga",
      ],
      "Región Metropolitana": [
        "Santiago",
        "Buin",
        "Colina",
        "Lampa",
        "Maipú",
        "Melipilla",
        "Puente Alto",
        "San Bernardo",
        "Talagante"
      ],
      "Región del Libertador General Bernardo O'Higgins": [
        "Rancagua",
        "Cachapoal",
        "Cardenal Caro",
        "Colchagua",
      ],
      "Región del Maule": [
        "Talca",
        "Cauquenes",
        "Curicó",
        "Linares",
        "Talca",
      ],
      "Región de Ñuble": ["Diguillín", "Itata", "Punilla"],
      "Región del Biobío": ["Concepción", "Arauco", "Bío Bío"],
      "Región de La Araucanía": ["Cautín", "Malleco"],
      "Región de Los Ríos": ["Valdivia", "Ranco"],
      "Región de Los Lagos": ["Lagos", "Osorno", "Chiloé"],
      "Región de Aysén del General Carlos Ibáñez del Campo": [
        "Aysén",
        "Capitán Prat",
        "Coihaique",
        "General Carrera",
      ],
      "Región de Magallanes y de la Antártica Chilena": [
        "Magallanes",
        "Antártica",
        "Tierra del Fuego",
        "Última Esperanza",
      ],
    },
  },
  Colombia: {
    departments: {
      "Amazonas": ["Leticia", "Puerto Nariño"],
      "Antioquia": ["Medellín", "Bello", "Envigado", "Itagüí", "Sabaneta", "Rionegro", "La Ceja", "Guarne", "Copacabana", "Belmira"],
      "Arauca": ["Arauca", "Arauquita", "Cravo Norte", "Fortul", "Puerto Rondón", "Saravena", "Tame"],
      "Atlántico": ["Barranquilla", "Soledad", "Malambo", "Puerto Colombia", "Sabanalarga", "Baranoa", "Galapa"],
      "Bolívar": ["Cartagena", "Magangué", "El Carmen de Bolívar", "San Juan Nepomuceno", "Arjona", "Turbaco"],
      "Boyacá": ["Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Ramiriquí", "Paipa", "Villa de Leyva"],
      "Caldas": ["Manizales", "Villamaría", "La Dorada", "Chinchiná", "Riosucio", "Supía", "Palestina"],
      "Caquetá": ["Florencia", "Belén de los Andaquíes", "Curillo", "El Paujil", "La Montañita", "San Vicente del Caguán"],
      "Casanare": ["Yopal", "Aguazul", "Villanueva", "Tauramena", "Monterrey", "Paz de Ariporo"],
      "Cauca": ["Popayán", "Santander de Quilichao", "Corinto", "Puerto Tejada", "Patía", "Bolívar"],
      "Cesar": ["Valledupar", "Aguachica", "Bosconia", "Curumaní", "La Jagua del Pilar", "Chimichagua"],
      "Chocó": ["Quibdó", "Istmina", "Tadó", "Riosucio", "Bahía Solano", "Acandí", "Unguía"],
      "Córdoba": ["Montería", "Cereté", "Lorica", "Planeta Rica", "Sahagún", "Tierralta"],
      "Cundinamarca": ["Bogotá", "Soacha", "Chía", "Zipaquirá", "Facatativá", "Mosquera", "Funza"],
      "Guainía": ["Inírida", "Barranco Minas", "Mapiripana", "Morichal Nuevo", "La Guadalupe"],
      "Guaviare": ["San José del Guaviare", "Calamar", "El Retorno", "Miraflores"],
      "Huila": ["Neiva", "Pitalito", "Garzón", "Campoalegre", "La Plata", "San Agustín"],
      "La Guajira": ["Riohacha", "Maicao", "Albania", "Fonseca", "Manaure", "Villanueva"],
      "Magdalena": ["Santa Marta", "Ciénaga", "Fundación", "Aracataca", "El Banco", "Plato"],
      "Meta": ["Villavicencio", "Acacías", "Granada", "Puerto López", "San Martín", "Cumaral"],
      "Nariño": ["Pasto", "Ipiales", "Tumaco", "Túquerres", "Samaniego", "La Unión"],
      "Norte de Santander": ["Cúcuta", "Ocaña", "Pamplona", "Villa del Rosario", "Los Patios", "Ábrego"],
      "Putumayo": ["Mocoa", "Puerto Asís", "Orito", "San Miguel", "Valle del Guamuez", "Sibundoy"],
      "Quindío": ["Armenia", "Calarcá", "La Tebaida", "Montenegro", "Quimbaya", "Salento"],
      "Risaralda": ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia", "Belén de Umbría"],
      "San Andrés y Providencia": ["San Andrés", "Providencia"],
      "Santander": ["Bucaramanga", "Floridablanca", "Barrancabermeja", "Girón", "Piedecuesta", "Rionegro"],
      "Sucre": ["Sincelejo", "Corozal", "Sampués", "San Marcos", "Coveñas", "Tolú"],
      "Tolima": ["Ibagué", "Espinal", "Honda", "Melgar", "Flandes", "Lérida"],
      "Valle del Cauca": ["Cali", "Buenaventura", "Palmira", "Tuluá", "Cartago", "Jamundí"],
      "Vaupés": ["Mitú", "Carurú", "Pacoa", "Papunahua", "Yavaraté"],
      "Vichada": ["Puerto Carreño", "La Primavera", "Cumaribo", "Santa Rosalía"]
    }
  },
  Ecuador: {
    departments: {
      "Azuay": ["Cuenca", "Gualaceo", "Paute", "Chordeleg", "El Pan", "Sígsig"],
      "Bolívar": ["Guaranda", "Chillanes", "Chimbo", "Echeandía", "San Miguel"],
      "Cañar": ["Azogues", "La Troncal", "Cañar", "Déleg", "Suscal"],
      "Carchi": ["Tulcán", "San Gabriel", "Mira", "Montúfar", "Bolívar"],
      "Chimborazo": ["Riobamba", "Alausí", "Chambo", "Chunchi", "Colta", "Guamote"],
      "Cotopaxi": ["Latacunga", "La Maná", "Pujilí", "Salcedo", "Saquisilí", "Sigchos"],
      "El Oro": ["Machala", "Pasaje", "Santa Rosa", "Arenillas", "Atahualpa", "Balsas"],
      "Esmeraldas": ["Esmeraldas", "Atacames", "Rioverde", "Quinindé", "Muisne", "Eloy Alfaro"],
      "Galápagos": ["Puerto Baquerizo Moreno", "Puerto Ayora", "Puerto Villamil"],
      "Guayas": ["Guayaquil", "Samborondón", "Durán", "Milagro", "Naranjal", "Playas"],
      "Imbabura": ["Ibarra", "Otavalo", "Cotacachi", "Pimampiro", "Urcuquí", "Antonio Ante"],
      "Loja": ["Loja", "Catamayo", "Cariamanga", "Calvas", "Gonzanamá", "Paltas"],
      "Los Ríos": ["Babahoyo", "Quevedo", "Ventanas", "Vinces", "Puebloviejo", "Urdaneta"],
      "Manabí": ["Portoviejo", "Manta", "Chone", "Montecristi", "Jipijapa", "Bahía de Caráquez"],
      "Morona Santiago": ["Macas", "Gualaquiza", "Limón Indanza", "Pablo Sexto", "Sucúa", "Huamboya"],
      "Napo": ["Tena", "Archidona", "El Chaco", "Quijos", "Carlos Julio Arosemena Tola"],
      "Orellana": ["Francisco de Orellana", "Aguarico", "La Joya de los Sachas", "Loreto"],
      "Pastaza": ["Puyo", "Mera", "Santa Clara", "Arajuno", "Shell"],
      "Pichincha": ["Quito", "Cayambe", "Mejía", "Pedro Moncayo", "Rumiñahui", "San Miguel de los Bancos"],
      "Santa Elena": ["Santa Elena", "La Libertad", "Salinas", "Manglaralto"],
      "Santo Domingo de los Tsáchilas": ["Santo Domingo", "La Concordia"],
      "Sucumbíos": ["Nueva Loja", "Cuyabeno", "Gonzalo Pizarro", "Lago Agrio", "Putumayo", "Shushufindi"],
      "Tungurahua": ["Ambato", "Baños", "Cevallos", "Mocha", "Patate", "Quero"],
      "Zamora Chinchipe": ["Zamora", "Loja", "Yantzaza", "Chinchipe", "Centinela del Cóndor", "Nangaritza"]
    }
  },
  Bolivia: {
    departments: {
      "Beni": ["Trinidad", "Riberalta", "Guayaramerín", "Reyes", "San Borja", "Santa Ana del Yacuma"],
      "Chuquisaca": ["Sucre", "Monteagudo", "Padilla", "Tomina", "Hernando Siles", "Yamparáez"],
      "Cochabamba": ["Cochabamba", "Quillacollo", "Sacaba", "Colcapirhua", "Tiquipaya", "Vinto"],
      "La Paz": ["La Paz", "El Alto", "Viacha", "Achacachi", "Copacabana", "Sorata"],
      "Oruro": ["Oruro", "Caracollo", "Huanuni", "Challapata", "Corque", "Poopó"],
      "Pando": ["Cobija", "Riberalta", "Guayaramerín", "Porvenir", "Bolpebra", "Filadelfia"],
      "Potosí": ["Potosí", "Llallagua", "Tupiza", "Villazón", "Cotagaita", "Uyuni"],
      "Santa Cruz": ["Santa Cruz de la Sierra", "Montero", "Warnes", "La Guardia", "Cotoca", "Portachuelo"],
      "Tarija": ["Tarija", "Yacuiba", "Bermejo", "Villamontes", "Padcaya", "Entre Ríos"]
    }
  },
  Panamá: {
    departments: {
      "Bocas del Toro": ["Bocas del Toro", "Changuinola", "Almirante", "Chiriquí Grande", "Isla Colón"],
      "Coclé": ["Penonomé", "Aguadulce", "Antón", "La Pintada", "Natá", "Olá"],
      "Colón": ["Colón", "Achiote", "Chagres", "Donoso", "Portobelo", "Santa Isabel"],
      "Chiriquí": ["David", "Boquete", "Bugaba", "Dolega", "Gualaca", "Remedios", "Tolé"],
      "Darién": ["La Palma", "Metetí", "Yaviza", "El Real", "Pinogana", "Santa Fe"],
      "Herrera": ["Chitré", "Las Minas", "Los Pozos", "Ocú", "Parita", "Pesé"],
      "Los Santos": ["Las Tablas", "Guararé", "Los Santos", "Macaracas", "Pedasí", "Pocrí"],
      "Panamá": ["Panamá", "San Miguelito", "Arraiján", "La Chorrera", "Pacora", "Chimán"],
      "Panamá Oeste": ["La Chorrera", "Arraiján", "Capira", "Chame", "San Carlos", "Antón"],
      "Veraguas": ["Santiago", "Atalaya", "Calobre", "Cañazas", "Las Palmas", "Montijo", "San Francisco", "Soná"]
    }
  }
};

export default locationData;