name: Docker Image CI

on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE_NAME: ceela_web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/proyecto_chile_frontend/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/proyecto_chile_frontend/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH Deploy to VPS
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          #key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/server/container
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ialbertocamilo --password-stdin
            docker pull ghcr.io/${{ github.repository_owner }}/proyecto_chile_web/${{ env.IMAGE_NAME }}:latest
            docker stack deploy -c docker-compose.yml bytestone
            docker service update --image ${{ env.IMAGE_NAME }}:latest bytestone_chile_web

